
image:
  repository: outlinewiki/outline
  tag: latest

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "kong"
  hosts:
    - host: outline.cicd.bitsb.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - outline.cicd.bitsb.dev
      secretName: outline-tls
  annotations:
    cert-manager.io/cluster-issuer: "bitsb-root-ca-issuer"

# OIDC Authentication with Authentik
auth:
  oidc:
    enabled: true
    clientId: "Jru1yoSOna9Z36u913sFf4on4txpVJYAqXYE2pkZ"
    authUri: "https://authentik.cicd.bitsb.dev/application/o/authorize/"
    tokenUri: "https://authentik.cicd.bitsb.dev/application/o/token/"
    userInfoUri: "https://authentik.cicd.bitsb.dev/application/o/userinfo/"
    displayName: "Authentik SSO"
    scopes:
      - openid
      - profile
      - email
    usernameClaim: "preferred_username"
    # Use existing secret for client secret (managed by ESO)
    existingSecret:
      name: "outline-oidc-credentials"
      clientSecretKey: "client-secret"

resources:
  limits:
    cpu: 300m
    memory: 756Mi
  requests:
    cpu: 100m
    memory: 256Mi

# Secure TLS handling - trust internal CA certificates
extraEnvVars:
  # Point to mounted CA certificate file
  NODE_EXTRA_CA_CERTS: /etc/ssl/certs/bitsb-ca.crt

# Mount your internal CA certificate
volumes:
  - name: bitsb-ca-cert
    secret:
      secretName: bitsb-root-ca-cert  # This secret should contain your CA cert

volumeMounts:
  - name: bitsb-ca-cert
    mountPath: /etc/ssl/certs/bitsb-ca.crt
    subPath: ca.crt
    readOnly: true

postgresql:
  enabled: true
  auth:
    username: outline
    password: outlinepass
    database: outline
    postgresPassword: outlinepass

redis:
  enabled: true
  auth:
    password: CHANGEME