apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: infrastructure-appset
    app.kubernetes.io/part-of: infrastructure
spec:
  generators:
  - list:
      elements:
      # Core Infrastructure Components (order matters)
      - name: kong
        namespace: ingress
        repoURL: https://kong.github.io/charts
        chart: kong
        targetRevision: 2.51.0
        priority: "300"

  template:
    metadata:
      name: "{{name}}"
      labels:
        app.kubernetes.io/name: "{{name}}"
        app.kubernetes.io/part-of: infrastructure
    spec:
      project: infrastructure

      source:
        repoURL: "{{repoURL}}"
        chart: "{{chart}}"
        targetRevision: "{{targetRevision}}"
        helm:
          valueFiles:
            - ../argocd/values/{{name}}/values.yaml
        
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - Validate=true
        - SkipDryRunOnMissingResource=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m