apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: infrastructure-appset
    app.kubernetes.io/part-of: infrastructure
spec:
  generators:
  - list:
      elements:
      - name: cert-manager
        namespace: cert-manager
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.16.2
        priority: "200"

      - name: kong
        namespace: ingress
        repoURL: https://kong.github.io/charts
        chart: kong
        targetRevision: 2.40.0
        priority: "300"

      - name: longhorn
        namespace: longhorn-system
        repoURL: https://charts.longhorn.io
        chart: longhorn
        targetRevision: 1.8.2
        priority: "400"

      # MinIO S3-compatible storage for Velero
      - name: minio
        namespace: minio
        repoURL: https://charts.min.io/
        chart: minio
        targetRevision: 5.4.0
        priority: "450"

      # Velero Backup/Restore
      - name: velero
        namespace: velero
        repoURL: https://vmware-tanzu.github.io/helm-charts
        chart: velero
        targetRevision: 10.0.10
        priority: "500"

  template:
    metadata:
      name: "{{name}}"
      labels:
        app.kubernetes.io/name: "{{name}}"
        app.kubernetes.io/part-of: infrastructure
    spec:
      project: infrastructure
      sources:
        - repoURL: "{{repoURL}}"
          chart: "{{chart}}"
          targetRevision: "{{targetRevision}}"
          helm:
            valueFiles:
              - $values/argocd/values/{{name}}/values.yaml
        - repoURL: https://github.com/bitsdalab/deployment.git
          targetRevision: feature/argocd-1
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - Validate=true
        - SkipDryRunOnMissingResource=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
