apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: infrastructure-appset
    app.kubernetes.io/part-of: infrastructure
spec:
  generators:
  - list:
      elements:
      # Core Infrastructure Components (order matters)
      - name: kong
        namespace: ingress
        repoURL: https://kong.github.io/charts
        chart: kong
        targetRevision: 2.51.0
        priority: "300"
      # Longhorn Distributed Storage
      - name: longhorn
        namespace: longhorn-system
        repoURL: https://charts.longhorn.io
        chart: longhorn
        targetRevision: 1.9.0
        priority: "400"

  template:
    metadata:
      name: "{{name}}"
      labels:
        app.kubernetes.io/name: "{{name}}"
        app.kubernetes.io/part-of: infrastructure
    spec:
      project: infrastructure

      sources:
        - repoURL: "{{repoURL}}"
          chart: "{{chart}}"
          targetRevision: "{{targetRevision}}"
          helm:
            valueFiles:
              - $values/argocd/values/{{name}}/values.yaml
        - repoURL: https://github.com/bitsdalab/deployment.git
          targetRevision: feature/argocd-1
          ref: values
        
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - Validate=true
        - SkipDryRunOnMissingResource=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m