apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: infrastructure
spec:
  description: Core infrastructure components (MetalLB, cert-manager, storage, networking)
  
  # Source repositories
  sourceRepos:
  - 'https://github.com/bitsdalab/deployment.git'
  - 'https://kong.github.io/charts'
  
  # Destination clusters and namespaces
  destinations:
  - namespace: ingress
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  
  roles: []
  
  syncWindows: []
