apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: platform
spec:
  description: Platform services (ArgoCD, monitoring, security, CI/CD tools)
  
  # Source repositories
  sourceRepos:
  - 'https://github.com/bitsdalab/deployment.git'
  - 'https://argoproj.github.io/argo-helm'
  - 'https://prometheus-community.github.io/helm-charts'
  - 'https://grafana.github.io/helm-charts'
  - 'https://charts.external-secrets.io'
  - 'https://hashicorp.github.io/vault-helm'
  
  # Destination clusters and namespaces
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: security
    server: https://kubernetes.default.svc
  - namespace: vault
    server: https://kubernetes.default.svc
  - namespace: external-secrets
    server: https://kubernetes.default.svc
  
  # Cluster-scoped resources (limited for security)
  clusterResourceWhitelist:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
  
  # Namespace-scoped resources
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  
  # RBAC
  roles:
  - name: platform-admin
    description: Full access to platform services
    policies:
    - p, proj:platform:platform-admin, applications, *, platform/*, allow
    - p, proj:platform:platform-admin, repositories, *, *, allow
    groups:
    - argocd:admin
  
  - name: platform-developer
    description: Limited access to platform services
    policies:
    - p, proj:platform:platform-developer, applications, get, platform/*, allow
    - p, proj:platform:platform-developer, applications, sync, platform/*, allow
    groups:
    - argocd:developer
