---
# ClusterSecretStore for Vault - configured for KV v2 secret engine "operations"
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-cluster-store-operations
spec:
  provider:
    vault:
      # Vault server endpoint - using internal Kubernetes service
      server: "http://vault.vault.svc.cluster.local:8200"
      
      # Path to the KV v2 secret engine named "operations"
      path: "operations"
      
      # Vault API version (v2 for KV v2 engines)
      version: "v2"
      
      # Authentication method - using root token
      auth:
        tokenSecretRef:
          name: "vault-root-token"
          key: "token"
          namespace: "external-secrets"
