apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  namespace: observability
spec:
  type: filebeat
  version: 8.12.2
  elasticsearchRef:
    name: elasticsearch
  kibanaRef:
    name: kibana
  config:
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        securityContext:
          runAsUser: 0
          fsGroup: 0
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        containers:
        - name: filebeat
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
