# cert-manager Configuration
# Version: v1.16.2
# Documentation: https://cert-manager.io/docs/

# Install CRDs as part of the chart
installCRDs: true

# Global configuration
global:
  # Cluster resource namespace
  leaderElection:
    namespace: cert-manager

# Resource limits for components
resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Webhook resources
webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

# CA Injector resources
cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi