---
# MetalLB IP Address Pool
# This defines the range of IP addresses MetalLB can assign to LoadBalancer services
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  # Update this range based on your network configuration
  # These should be available IPs in your network that won't conflict with DHCP
  - 192.168.1.240-192.168.1.250
  autoAssign: true

---
# L2Advertisement configuration
# This tells MetalLB to advertise the IPs using Layer 2 (ARP)
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool
