authentik:
  secret_key: "REPLACE_ME_WITH_A_SECRET_KEY"

server:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  ingress:
    enabled: true
    ingressClassName: kong
    hosts:
      - authentik.cicd.bitsb.dev
    tls:
      - secretName: authentik-tls
        hosts:
          - authentik.cicd.bitsb.dev
    annotations:
      cert-manager.io/cluster-issuer: "bitsb-root-ca-issuer"

worker:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi