apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability
  namespace: argocd
  labels:
    app.kubernetes.io/name: observability-appset
    app.kubernetes.io/part-of: observability
spec:
  generators:
  - list:
      elements:
      # SigNoz: Modern open-source observability platform (traces, metrics, logs)
      - name: signoz
        namespace: observability
        repoURL: https://charts.signoz.io
        chart: signoz
        targetRevision: 0.88.3
        priority: "100"
      # kube-prometheus-stack: Complete monitoring stack - Updated version
      #- name: kube-prometheus-stack
      #  namespace: observability
      #  repoURL: https://prometheus-community.github.io/helm-charts
      #  chart: kube-prometheus-stack
      #  targetRevision: 76.2.1  # Updated to latest
      #  priority: "200"
      ## Blackbox Exporter: Probes endpoints for availability and performance
      #- name: blackbox-exporter
      #  namespace: observability
      #  repoURL: https://prometheus-community.github.io/helm-charts
      #  chart: prometheus-blackbox-exporter
      #  targetRevision: 8.15.0
      #  priority: "300"
      ## Zipkin: Distributed tracing for microservices
      #- name: zipkin
      #  namespace: observability
      #  repoURL: https://openzipkin.github.io/zipkin
      #  chart: zipkin
      #  targetRevision: 0.1.2  # Verify this version
      #  priority: "400"
      ## Thanos: Long-term, highly available metrics storage - Deploy after Prometheus
      #- name: thanos
      #  namespace: observability
      #  repoURL: https://charts.bitnami.com/bitnami  # Consider switching to official
      #  chart: thanos
      #  targetRevision: 17.2.6  # Bitnami version, or use thanos-io.github.io
      #  priority: "500"
  template:
    metadata:
      name: "{{name}}"
      labels:
        app.kubernetes.io/name: "{{name}}"
        app.kubernetes.io/part-of: observability
    spec:
      project: observability
      sources:
        - repoURL: "{{repoURL}}"
          chart: "{{chart}}"
          targetRevision: "{{targetRevision}}"
          helm:
            valueFiles:
              - $values/argocd/values/{{name}}/values.yaml
        - repoURL: https://github.com/bitsdalab/deployment.git
          targetRevision: feature/monitoring
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - Validate=true
        - SkipDryRunOnMissingResource=true
        - Replace=true               # Handle CRD updates
        - ServerSideApply=true       # Better CRD handling
        - RespectIgnoreDifferences=true
        retry:
          limit: 5                   # Increased retry limit
          backoff:
            duration: 10s            # Increased initial duration
            factor: 2
            maxDuration: 5m          # Increased max duration