apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: metallb
    app.kubernetes.io/part-of: infrastructure
spec:
  project: infrastructure
  
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.15.2
    helm:
      valueFiles:
      - $values/stacks/values/metallb/values.yaml
  
  sources:
  - repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.15.2
  - repoURL: https://github.com/bitsdalab/deployment
    targetRevision: HEAD
    ref: values
    
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
