# Jenkins CI/CD Configuration
controller:
  
  # Resource requests and limits
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

  # Ingress configuration
  ingress:
    enabled: true
    ingressClassName: kong
    hostName: jenkins.cicd.bitsb.dev
    tls:
      - secretName: jenkins-tls
        hosts:
          - jenkins.cicd.bitsb.dev
    annotations:
      cert-manager.io/cluster-issuer: "bitsb-root-ca-issuer"

  # Java options for better performance
  javaOpts: "-Xmx1g -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport"

  # Install minimum required plugins with specific versions
  installPlugins:
    # Kubernetes support
    - kubernetes:4200.v1dd44f5b_1cf9
    # Source control
    - git:5.2.1
    # Blue Ocean UI
    - blueocean:1.30.18
    # Configuration as Code
    - configuration-as-code:1775.v810dc950b_514

# Persistence
persistence:
  enabled: true
  size: 20Gi

# Agent configuration
agent:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
