
image:
  repository: outlinewiki/outline
  tag: latest

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  hosts:
    - host: outline.cicd.bitsb.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - outline.cicd.bitsb.dev
      secretName: outline-tls
  annotations:
    cert-manager.io/cluster-issuer: "bitsb-root-ca-issuer"

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

env:
  - name: "DATABASE_URL"
    value: "postgresql://outline:CHANGEME@localhost:5432/outline"
  - name: "REDIS_URL"
    value: "redis://:CHANGEME@localhost:6379"
  - name: "SECRET_KEY"
    value: "CHANGEME"

postgresql:
  enabled: true
  auth:
    username: outline
    password: CHANGEME
    database: outline
    postgresPassword: CHANGEME

redis:
  enabled: true
  auth:
    password: CHANGEME