apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform-appset
    app.kubernetes.io/part-of: platform
spec:
  generators:
  - list:
      elements:
      # Platform Services
      - name: argocd
        namespace: argocd
        chart: argo/argo-cd
        version: 8.1.3
        priority: "100"

  template:
    metadata:
      name: "{{name}}"
      labels:
        app.kubernetes.io/name: "{{name}}"
        app.kubernetes.io/part-of: platform
    spec:
      project: platform
      
      source:
        repoURL: https://github.com/bitsdalab/infra
        targetRevision: HEAD
        path: deployment/argocd/applications/platform/{{name}}
        
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - Validate=true
        - SkipDryRunOnMissingResource=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
