apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-prep
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/bitsdalab/deployment.git
    targetRevision: feature/argocd-1
    path: argocd/applications/infrastructure/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Validate=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
