apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-prerequisites
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/bitsdalab/deployment.git
    targetRevision: feature/argocd-final
    path: argocd/applications/infrastructure/velero
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
