apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/part-of: infrastructure
spec:
  project: infrastructure
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: 10.1.10
      helm:
        valueFiles:
          - $values/argocd/values/infrastructure/velero/values.yaml
        ignoreMissingValueFiles: true
    - repoURL: https://github.com/bitsdalab/deployment.git
      targetRevision: feature/monitoring
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Validate=true
      - SkipDryRunOnMissingResource=true
      # Velero-specific sync options for handling upgrade hooks
      - Replace=true
      - Force=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
