# Velero values.yaml for MinIO backend
credentials:
  useSecret: true
  existingSecret: velero-minio-creds
configuration:
  backupStorageLocation:
    - name: minio-node-1
      provider: aws
      bucket: velero
      config:
        region: minio
        s3ForcePathStyle: "true"
        s3Url: http://bits-node-1:9001
    - name: minio-node-2
      provider: aws
      bucket: velero
      config:
        region: minio
        s3ForcePathStyle: "true"
        s3Url: http://bits-node-2:9001
initContainers: []
# Optionally, set schedules, nodeAgent, etc. as needed
