# Velero values.yaml for MinIO backend
credentials:
  useSecret: true
  existingSecret: velero-minio-creds
  secretContents:
    cloud: |
      [default]
      aws_access_key_id = minioadmin
      aws_secret_access_key = minioadmin123
configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      config:
        region: minio
        s3ForcePathStyle: "true"
        s3Url: http://minio.minio.svc.cluster.local:9000
  volumeSnapshotLocation:
    - name: default
      provider: aws
      config:
        region: minio
initContainers: []
# Optionally, set schedules, nodeAgent, etc. as needed
