---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-oidc-credentials
  namespace: outline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store-operations
    kind: ClusterSecretStore
  target:
    name: outline-oidc-credentials
    creationPolicy: Owner
  data:
  # Fetch Authentik OIDC credentials from Vault
  - secretKey: OIDC_CLIENT_ID
    remoteRef:
      key: outline/authentik
      property: client_id
  
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      key: outline/authentik
      property: client_secret
  
  - secretKey: OIDC_AUTH_URI
    remoteRef:
      key: outline/authentik
      property: auth_uri
  
  - secretKey: OIDC_TOKEN_URI
    remoteRef:
      key: outline/authentik
      property: token_uri
  
  - secretKey: OIDC_USERINFO_URI
    remoteRef:
      key: outline/authentik
      property: userinfo_uri
