---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-secrets
  namespace: outline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-cluster-store-operations
    kind: ClusterSecretStore
  target:
    name: outline-secrets
    creationPolicy: Owner
  data:
  # Fetch Outline secret key from Vault
  # This is the master encryption key for the database
  - secretKey: secret-key
    remoteRef:
      key: outline/secrets
      property: secret_key
  
  # Fetch Outline utils secret from Vault
  # This is used to authenticate requests to the cron utility endpoint
  - secretKey: utils-secret
    remoteRef:
      key: outline/secrets
      property: utils_secret
