signoz:
  ingress:
    enabled: true
    className: kong
    hosts:
      - host: signoz.ops.bitsb.dev
        paths:
          - path: /
            pathType: Prefix
            port: 8080
    tls:
      - secretName: signoz-tls
        hosts:
          - signoz.ops.bitsb.dev
    annotations:
      cert-manager.io/cluster-issuer: "bitsb-root-ca-issuer"
      cert-manager.io/common-name: "signoz.ops.bitsb.dev"
      konghq.com/protocols: "https"
      konghq.com/https-redirect-status-code: "301"
      konghq.com/preserve-host: "true"
      konghq.com/strip-path: "false"
  frontend:
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    env:
      SIGNOZ_JWT_SECRET: "4CRRriBO7AX3eKBYHXyRV1bU"
  queryService:
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  otelCollector:
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    # Enable log collection - SigNoz already has built-in log support
    # The otelCollector has httplogreceiver for logs and proper pipelines
    extraVolumes:
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
    extraVolumeMounts:
      - name: varlogpods
        mountPath: /var/log/pods
        readOnly: true
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
  clickhouse:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: longhorn
