global:
  ingress:
    enabled: true
    ingressClassName: kong
    hosts:
      - signoz.ops.bitsb.dev
    tls:
      - secretName: signoz-tls
        hosts:
          - signoz.ops.bitsb.dev
    annotations:
      cert-manager.io/cluster-issuer: "bitsb-root-ca-issuer"
      cert-manager.io/common-name: "signoz.ops.bitsb.dev"
      konghq.com/protocols: "https"
      konghq.com/https-redirect-status-code: "301"
      konghq.com/preserve-host: "true"
      konghq.com/strip-path: "false"
frontend:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
query-service:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
otel-collector:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
clickhouse:
  persistence:
    enabled: true
    size: 50Gi
    storageClass: longhorn
