apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/part-of: infrastructure
spec:
  project: infrastructure
  
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.8.2
    helm:
      valueFiles:
      - $values/stacks/values/longhorn/values.yaml
  
  sources:
  - repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.8.2
  - repoURL: https://github.com/bitsdalab/deployment
    targetRevision: HEAD
    ref: values
    
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
