apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: longhorn-deps-installer
  namespace: kube-system
  labels:
    app: longhorn-deps-installer
spec:
  selector:
    matchLabels:
      app: longhorn-deps-installer
  template:
    metadata:
      labels:
        app: longhorn-deps-installer
    spec:
      hostPID: true
      hostNetwork: true
      tolerations:
      - operator: Exists
      containers:
      - name: installer
        image: ubuntu:24.04
        securityContext:
          privileged: true
        command:
        - /bin/bash
        - -c
        - |
          apt-get update -qq && apt-get install -y util-linux
          echo "=== Installing open-iscsi on node $(hostname) ==="
          nsenter --target 1 --mount --uts --ipc --net --pid -- bash << 'HOSTSCRIPT'
            set -e
            echo "Updating package list..."
            apt-get update -qq
            echo "Installing open-iscsi..."
            DEBIAN_FRONTEND=noninteractive apt-get install -y open-iscsi
            echo "Enabling iscsid service..."
            systemctl enable iscsid
            systemctl start iscsid
            echo "Verifying installation..."
            iscsiadm --version
            echo "open-iscsi installed successfully!"
          HOSTSCRIPT
          echo "Installation completed on $(hostname)"
          sleep infinity
      restartPolicy: Always
