apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/part-of: infrastructure
spec:
  project: infrastructure
  
  source:
    repoURL: https://kong.github.io/charts
    chart: kong
    targetRevision: 2.40.0
    helm:
      valueFiles:
      - $values/deployment/stacks/values/kong/values.yaml
  
  sources:
  - repoURL: https://kong.github.io/charts
    chart: kong
    targetRevision: 2.40.0
  - repoURL: https://github.com/bitsdalab/infra
    targetRevision: HEAD
    ref: values
    
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
